//
//  EnvironmentStorage.swift
//
//
//  Created by Wouter Hennen on 14/06/2023.
//

import SwiftSyntax
import SwiftSyntaxMacros

public struct EnvironmentStorage: MemberAttributeMacro {
    public static func expansion(
        of node: AttributeSyntax,
        attachedTo declaration: some DeclGroupSyntax,
        providingAttributesFor member: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [AttributeSyntax] {

        // Only attach macro if member is a variable.
        // Otherwise, it will also get attached to the structs generated by @EnvironmentValue
        guard member.is(VariableDeclSyntax.self) else {
            return []
        }

        return [
            AttributeSyntax(
                atSignToken: .atSignToken(),
                attributeName: SimpleTypeIdentifierSyntax(name: .identifier("EnvironmentValue"))
            )
        ]
    }
}
